print('ola mundo')
print('testando')
print('indo pro git na net')
print ('indo pro pc')
print('sera?')
print ('voltando pro git')
print('sera que agora vai?')
print('se chegar no pc estamos 1 a zero)
print('agora tem que subir pro pc')